apiVersion: batch/v1
kind: CronJob
metadata:
  name: clean-db
  namespace: vitex-k8s
  labels:
    app.kubernetes.io/name: clean-db
    app.kubernetes.io/part-of: vitex-k8s
spec:
  # 3 o'clock everyday
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: clean-db
              image: yourdockerrepo/vitex-stats-server:1.12
              command: ["flask", "manage", "clean-db-days-before", "360"]
              imagePullPolicy: IfNotPresent
              env:
                - name: FLASK_CONFIG
                  value: /etc/vitex-stats-server/flask_config.py
                - name: FLASK_ENV
                  value: production
              volumeMounts:
                - mountPath: /etc/vitex-stats-server
                  name: flask-config
                  readOnly: true
          volumes:
            - name: flask-config
              configMap:
                name: vitex-stats-server

          restartPolicy: OnFailure
