apiVersion: batch/v1
kind: Job
metadata:
  name: download-chunks-b20220101
  namespace: vitex-k8s
  labels:
    app.kubernetes.io/name: download-chunks
    app.kubernetes.io/part-of: vitex-k8s
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 86400
  template:
    spec:
      containers:
        - name: download-chunks
          image: yourdockerrepo/vitex-stats-server:1.12
          command: ["flask", "manage", "chunk-download", "2022-01-01"]
          env:
            - name: FLASK_CONFIG
              value: /etc/vitex-stats-server/flask_config.py
            - name: FLASK_ENV
              value: production
          volumeMounts:
            - mountPath: /etc/vitex-stats-server
              name: flask-config
              readOnly: true
      volumes:
        - name: flask-config
          configMap:
            name: vitex-stats-server
      restartPolicy: Never
