apiVersion: v1
kind: Service
metadata:
  name: govite-chain
  namespace: vitex-k8s
  labels:
    app.kubernetes.io/name: govite
    app.kubernetes.io/part-of: vitex-k8s
spec:
  type: ClusterIP
  ports:
    - port: 48132
      name: govite-http
      targetPort: http
  selector:
    app.kubernetes.io/name: govite
    app.kubernetes.io/part-of: vitex-k8s
