kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: vitex-k8s
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: vitex-k8s
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
