kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: vitex-k8s
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: vitex-k8s
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/pv-postgres-data"
